DEFINES+=PROJECT_CONF_H=\"project-conf.h\"

HAVE_BANKING=1
UIP_CONF_IPV6=1
UIP_CONF_RPL=1
OFFSET_FIRMWARE=1
STACK_CONF_DEBUGGING=1

PROJECT_SOURCEFILES += mqtt-sn.c

CONTIKI_PROJECT = atividade6 atividade6cli#client server atividade4o servidorat4 ativ4


all: example

CONTIKI = ../../..

include $(CONTIKI)/Makefile.include
